---
title: evpn-clos2
---
graph TD
  spine1---leaf1
  spine2---leaf1
  spine1---leaf2
  spine2---leaf2
  spine1---leaf3
  spine2---leaf3
  spine1---leaf4
  spine2---leaf4
  spine1---leaf5
  spine2---leaf5
  spine1---leaf6
  spine2---leaf6
  spine1---leaf7
  spine2---leaf7
  spine1---leaf8
  spine2---leaf8
  leaf1---host1
  leaf2---host1
  leaf3---host2
  leaf4---host2
  leaf5---host3
  leaf6---host3
  leaf7---host4
  leaf8---host4